version: "3.9"

services:

  heroes_spring_api:
    container_name: java_app
    image: apirest-java_app:1.0.0
    build: .
    ports:
      - 9090:9090
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/heroes_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - heroes_db 
      
  heroes_db:
    container_name: heroes_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heroes_db
  
